### ISSUE TITLE
spec out VMs

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/feeder#26]

**Comment by dayne** [comment]
@teknofire -- Can you clarify this one.

**Comment by teknofire** [comment]
I have no clue, there are a bunch of tickets in this repo that I'm not really sure why they are here.

**Comment by dayne** [comment]
Thanks Will. Going to close this then.

Close any of those others that don't make sense to you.  Update or reframe any that you do know are needed but don't make sense now while yoir head is in that mode/topic.
